### ISSUE TITLE
Getting module error

### ISSUE THREAD

**Issue by nikasvan** [JoeRoddy/react-native-tag-autocomplete#1]
Hi, Just installed and when I imported it in the app, I am getting this error: 

[image](http://prntscr.com/gj04qb)
Did everything presented in the error but no luck, any suggestions?

**Comment by JoeRoddy** [comment]
Hey man, sorry, just saw this.   I think the link is dead, can you upload it again and I'll take a look?

**Comment by JoeRoddy** [comment]
Hey Nick!  Sorry, just saw this last night.  

I think I fixed the issue.  Can you update this package, then rm -rf node_modules && npm i

Let me know whether that fixes things.

**Comment by nikasvan** [comment]
Hey Joe, It's fixed now. 

Thanks for quick help and for creating this awesome component.

**Comment by JoeRoddy** [comment]
Thank **you** for opening the issue.  I probably would've never realized if you hadn't created this :smile:
