### ISSUE TITLE
Clarification: Is there any way to limit the selected tags in above the input hashtag box

### ISSUE THREAD

**Issue by nihp** [JoeRoddy/react-native-tag-autocomplete#10]
Is there any way to limit the selected tag lines upto 2 lines.

Here I has 4 lines and also we can add more tags. Refer the below attachment
![screen shot 2018 07 13 at 4 45 45 pm 1](https://user-images.githubusercontent.com/36992338/42689257-206145c4-86bd-11e8-83ba-fbddffd0a05d.png)

**Comment by JoeRoddy** [comment]
Yep! Take a look at the Readme, theres a function called `renderTags()`.  You can override the default render and add your own custom functionaliy.  I believe one of the examples implements it as well.
