### ISSUE TITLE
If the user move the pointer in-between the word and clicks double space, it converting to full stop

### ISSUE THREAD

**Issue by nihp** [JoeRoddy/react-native-tag-autocomplete#11]
1. If a user place the cursor in-between a word and then clicks double space, it change to full stop.

2. After enter the words it remains in the input box.
![screen shot 2018-07-16 at 5 41 19 pm](https://user-images.githubusercontent.com/36992338/42758039-b452066a-891f-11e8-9153-3b4da28dc51b.png)
![screen shot 2018-07-16 at 5 40 55 pm](https://user-images.githubusercontent.com/36992338/42758040-b4854ff2-891f-11e8-9768-0044d7da4119.png)

**Comment by JoeRoddy** [comment]
Should be fixed, update and try again.  Will create a tag and clear the input box.

**Comment by nihp** [comment]
But the double space creating a fullstop
