### ISSUE TITLE
Unable to see the textInput field need to scroll up to see the user input

### ISSUE THREAD

**Issue by nihp** [JoeRoddy/react-native-tag-autocomplete#22]
I am using AutoTags, but here  I am facing issue with the Keyboard. If I pointed the pointer inside the text input box the keyboard hide the inputbox. Here I need to scroll up the page to see the input field. 

Note: I have used ScrollView inside the KeyboardAvoidingView

**Comment by JoeRoddy** [comment]
Going to close this one in favor of your other issue, let's try to keep the conversation in that one :D

https://github.com/JoeRoddy/react-native-tag-autocomplete/issues/8
