### ISSUE TITLE
"react-native-tag-autocomplete" not working after React-Native version upgrade to 0.60 both Android & iOS

### ISSUE THREAD

**Issue by ksreepal** [JoeRoddy/react-native-tag-autocomplete#26]
@JoeRoddy we are using RN >0.60
 As ListView is deprecated we are unable to use react-native-tag-autocomplete both in Android & iOS. Please provide me a fix. Thanks in advance

**Comment by JoeRoddy** [comment]
@ksreepal Should be fixed in v1.0.22, thanks for the heads up.  Please reopen the issue if you run into any problems :)

**Comment by ksreepal** [comment]
> @ksreepal Should be fixed in v1.0.22, thanks for the heads up. Please reopen the issue if you run into any problems :)

@JoeRoddy Thanks for the update, works like a charm :)
