### ISSUE TITLE
entered text is not on the suggestions

### ISSUE THREAD

**Issue by vvavepacket** [JoeRoddy/react-native-tag-autocomplete#4]
How do we make the same effect (circled) if the text entered is not in one of the suggestions array? In this case, 'tambayan' is not in the list. Thank you.

![image](https://user-images.githubusercontent.com/8295642/32838036-acb096c6-c9dd-11e7-9381-7fad110d067d.png)

**Comment by JoeRoddy** [comment]
This sounds like a good feature.  With things like email, you may want to enter someone who isn't in your address book already, etc. 

How would you expect it to work?  When the user presses return / enter, then turn it into a tag?

**Comment by vvavepacket** [comment]
yes, when a user presses enter. thats a good idea

Ideally, we should support to modes.. first mode is enter key,, the second mode is whenever there is a space.

**Comment by JoeRoddy** [comment]
Good idea, so we could add two props: 

addTagOnEnter = {bool: default - true }
addTagOnSpace = {bool: default - false }

Then it can be customized to whichever combinations they choose. 

We'd need to add an [onSubmitEditing](https://facebook.github.io/react-native/docs/textinput.html#onsubmitediting) handler for addTagOnEnter, and add a check in the handleInput function (maybe there is a better way?), something like:

if(this.props.addTagOnSpace && text.charAt(text.length-1) === " ") { 
   return this.addTag(text) 
}

Let me know if you want to take a shot at doing  a PR.  If not, then no worries.  Thanks for all of your help improving the component! :D

**Comment by nihp** [comment]
I need this feature for my app. Could you please push this above code?

**Comment by JoeRoddy** [comment]
Feature added w/ [this commit](https://github.com/JoeRoddy/react-native-tag-autocomplete/commit/94fa174158934fdb17fff72ea72fc3d81792bed1).

I've updated [this example](https://github.com/JoeRoddy/react-native-tag-autocomplete/blob/master/examples/CustomExample.js)  with an implementation.
 
For `enter` creation, simply pass an `onCustomTagCreated` prop, which is a function that receives the user input as a string, which you can use to create whatever object you want.

For `space`, pass `createTagOnSpace`, and ensure you've passed the above function.
