### ISSUE TITLE
How to highlight the scrollview indicator in rendered tags

### ISSUE THREAD

**Issue by nihp** [JoeRoddy/react-native-tag-autocomplete#43]
Scrolling is not user friendly for the liststyle. Any option to highlight the scrolling indicator?

**Comment by JoeRoddy** [comment]
@nihp This module uses react-native-autocomplete-input as a dependency, so they might have some props that can help you.

https://github.com/mrlaessig/react-native-autocomplete-input#props

All the props that you pass down to this component get forwarded along to that one.

Specifically, I would look at `listContainerStyle`, and `listStyle`

**Comment by JoeRoddy** [comment]
going to close this, let me know if that helped at all
