### ISSUE TITLE
New suggestions not shown as tags after click on the enter button, it get hiding above the input text box

### ISSUE THREAD

**Issue by nihp** [JoeRoddy/react-native-tag-autocomplete#7]
I have entered a new word in the suggestions. But it not shown as tag it goes above the input text(not shown in the input text box).

1. Enter any input
2. It not shown in the input text field
3. Again search for the same word (It rendering the word)
4. Form as a tag

**Comment by JoeRoddy** [comment]
Could you post a small code example that reproduces it?

I'm thinking the styles are probably causing the hidden effect somewhere, but I'd have to see the code.

**Comment by nihp** [comment]
@JoeRoddy Thanks for your reply. This issue was fixed by below mentioned code changes. 

Below snippet is used by me to create the new inputs to add as tag.
 ```
 onCustomTagCreated = userinput => {
    //user pressed enter, create a new tag from their input
    var xxxxx = {
      name: userinput
    };
    this.setState({ suggestions: this.state.suggestions.concat([ xxxxx ]) });
    this.handleAddition( xxxxx );
  };

```
**I am getting a new issue (i.e) If I click enter without typing any thing in the input text box it shows as tag.** Refer the attached image
![screen shot 2018-07-02 at 9 45 34 am](https://user-images.githubusercontent.com/36992338/42145198-86a67090-7ddd-11e8-9dd1-6ba21c458ad3.png)

**Comment by JoeRoddy** [comment]
just add this as  the first line of the function:
`if (!userInput || userInput === "") return;`

^That way the tag wont be created if they type nothing.  I'll add that line to the example, thanks.
