### ISSUE TITLE
Unable to see the userInput, because the keyboard is shown above the input box

### ISSUE THREAD

**Issue by nihp** [JoeRoddy/react-native-tag-autocomplete#8]
While I am typing any input in the input field I can't able to see the input text box. The keyboard shown above the input textbox while using this package. Kindly suggest any solution for me
![screen shot 2018-07-02 at 10 46 18 am](https://user-images.githubusercontent.com/36992338/42146407-31a76862-7de5-11e8-9212-d50a6d69c72e.png)

**Comment by JoeRoddy** [comment]
Take a look at [KeyboardAvodingView](https://facebook.github.io/react-native/docs/keyboardavoidingview.html), that should hopefully help you here.

**Comment by nihp** [comment]
@JoeRoddy 

I have used react-native-keyboard-aware-scroll-view package

**Comment by nihp** [comment]
KeyboardAvodingView not worked for me. So I have reopened this.

**Comment by nihp** [comment]
Also If I click on the return in the simulator keyboard is still showing in UI.

**Comment by JoeRoddy** [comment]
Try to replace the AutoTags component with a regular textinput to prove that the textinput correctly moves when the keyboard opens.  My guess is that it's not an issue with this component, but some small implementation issue with KeyboardAvoidingView.

Check [this](https://medium.freecodecamp.org/how-to-make-your-react-native-app-respond-gracefully-when-the-keyboard-pops-up-7442c1535580) out if you haven't already.

**Comment by nihp** [comment]
But after click on the return in the keyboard, it not get closed. I need to click any where in my UI then only it get closing

**Comment by nihp** [comment]
Keyboard not closed if the user not give any input inside the hashtag container and then clicks on the return tab

**Comment by nihp** [comment]
KeyBoardAvoidingView is giving space below the input box

**Comment by JoeRoddy** [comment]
> I am using AutoTags, but here I am facing issue with the Keyboard. If I pointed the pointer inside the text input box the keyboard hide the inputbox. Here I need to scroll up the page to see the input field.
> 
> Note: I have used ScrollView inside the KeyboardAvoidingView

@nihp Can you upload a gist with a small example of a component KeyboardAvoidingView not working?  Thanks!

**Comment by nihp** [comment]
@JoeRoddy I have lot of inputText boxes in my screen. At last it will show the Tags inputbox last. If you saw this inputbox above. Add many text input box field and type the input from the AutoTags. Here you need to move the page up and need to see the inputbox.

https://snack.expo.io/@niph/hashtags

**Comment by nihp** [comment]
@JoeRoddy  Can you able to provide any solution for this.

**Comment by JoeRoddy** [comment]
@nihp were you able to solve your issue?  I received a couple email notifications, but I don't see your comment on github.

**Comment by nihp** [comment]
No, not yet.  I will give a sample reproducible example. Thanks

**Comment by nihp** [comment]
@JoeRoddy 

Refer the attached expo for iOS. If I click on the Hashtag input box it gets hidden behind the keyboard. Here I have used KeyboardAvoidingView with behaviour padding.

https://snack.expo.io/@niph/hashtag

**Comment by JoeRoddy** [comment]
@nihp thanks for the link.  I'll take a look

**Comment by nihp** [comment]
@JoeRoddy Thanks

**Comment by nihp** [comment]
@JoeRoddy 

The above keyboard issue get fixed after using react-native-keyboard-aware-scrollview.

Thanks

https://snack.expo.io/@niph/keyboardaware

**Comment by JoeRoddy** [comment]
Awesome!  Thanks for the update @nihp 

Glad you were able to figure it out :D
