### ISSUE TITLE
Tag not created if the user place the pointer in-between the word and clicks space 

### ISSUE THREAD

**Issue by nihp** [JoeRoddy/react-native-tag-autocomplete#9]
If the user place the pointer in-between any word and click on the space means, it not create the tag.

createTagOnSpace ={true} not worked here. 
![screen shot 2018-07-12 at 5 07 54 pm](https://user-images.githubusercontent.com/36992338/42630900-260954f2-85f6-11e8-921c-2d79afb77811.png)

**Comment by JoeRoddy** [comment]
This is the intended behavior. createTagOnSpace will only work if it's the last space.  

If you want to change that, you could fork the repo and change [line 52 of index.js](https://github.com/JoeRoddy/react-native-tag-autocomplete/blob/28e4ed4365330ecca0a518a5e693cba109452a53/index.js#L52)

Right now it just checks if the last character is a space.  So you'd want it to check if any char is a space.  You would probably want to change it to something like:
```
.... &&  text.includes(" ") ) {
 //create tag 
}

```
